version: '3.8'

services:
  wp_db:
    image: mysql:8.0.21
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass

  wp:
    depends_on:
      - wp_db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: db-user
      WORDPRESS_DB_PASSWORD: db-pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html

  phpmyadmin:
    depends_on:
      - wp_db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: wp_db
    restart: always
    ports:
      - "8080:80"

volumes:
   db_data: {}
